version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - type: volume
        source: dbdev
        target: /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MPA_PORT: 3306
    links:
      - db
    depends_on:
      - db

volumes:
  dbdev:
    external: true
