version: "3.8"

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - type: volume
        source: dbdev
        target: /var/lib/mysql

volumes:
  dbdev:
    external: true
